version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80"      # HTTP traffic
      - "8080:8080"  # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Traefik needs Docker access
      - ./traefik.yml:/etc/traefik/traefik.yml     # Static configuration
      - ./config:/etc/traefik/config               # Dynamic config folder
    networks:
      - web

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`localhost`)"
      - "traefik.http.services.webserver.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    driver: bridge
