global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true  # Enables the Traefik dashboard

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false  # Only proxy containers with explicit labels
  file:
    directory: "/etc/traefik/config"
    watch: true  # Watch for config changes
