FROM traefik:v3.3.3

# Copy static configuration file (traefik.yml)
COPY traefik.yml /etc/traefik/traefik.yml

# Copy dynamic configuration file (dynamic.yml)
COPY dynamic.yml /etc/traefik/dynamic.yml
