services:
  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    ports:
      - "80:80"       # For HTTP traffic (e.g., your 'web' entrypoint)
      - "8080:8080"   # For the Traefik dashboard
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./dynamic.yml:/etc/traefik/dynamic.yml:ro"
    restart: unless-stopped
